In [23]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.preprocessing import StandardScaler

In [24]:
df = pd.read_csv('Switzerland.csv')

In [25]:
df.head()

   32  1  1.1   95  0  ? 0.1  127 0.2   .7 1.2 ?.1 ?.2  1.3
0  34  1    4  115  0  ?   ?  154   0   .2   1   ?   ?    1
1  35  1    4    ?  0  ?   0  130   1    ?   ?   ?   7    3
2  36  1    4  110  0  ?   0  125   1    1   2   ?   6    1
3  38  0    4  105  0  ?   0  166   0  2.8   1   ?   ?    2
4  38  0    4  110  0  0   0  156   0    0   2   ?   3    1

In [26]:
df.columns=['age', 'sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','num']
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,34,1,4,115,0,?,?,154,0,.2,1,?,?,1
1,35,1,4,?,0,?,0,130,1,?,?,?,7,3
2,36,1,4,110,0,?,0,125,1,1,2,?,6,1
3,38,0,4,105,0,?,0,166,0,2.8,1,?,?,2
4,38,0,4,110,0,0,0,156,0,0,2,?,3,1

In [27]:
df.replace("?",np.nan,inplace=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,34,1,4,115,0,NaN,NaN,154,0,.2,1,NaN,NaN,1
1,35,1,4,NaN,0,NaN,0,130,1,NaN,NaN,NaN,7,3
2,36,1,4,110,0,NaN,0,125,1,1,2,NaN,6,1
3,38,0,4,105,0,NaN,0,166,0,2.8,1,NaN,NaN,2
4,38,0,4,110,0,0,0,156,0,0,2,NaN,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,70,1,4,115,0,0,1,92,1,0,2,NaN,7,1
118,70,1,4,140,0,1,0,157,1,2,2,NaN,7,3
119,72,1,3,160,0,NaN,2,114,0,1.6,2,2,NaN,0
120,73,0,3,160,0,0,1,121,0,0,1,NaN,3,1
121,74,1,2,145,0,NaN,1,123,0,1.3,1,NaN,NaN,1

In [28]:
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [29]:
print(df)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     34    1   4     115.0     0  NaN      NaN    154.0    0.0      0.2
1     35    1   4       NaN     0  NaN      0.0    130.0    1.0      NaN
2     36    1   4     110.0     0  NaN      0.0    125.0    1.0      1.0
3     38    0   4     105.0     0  NaN      0.0    166.0    0.0      2.8
4     38    0   4     110.0     0  0.0      0.0    156.0    0.0      0.0
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
117   70    1   4     115.0     0  0.0      1.0     92.0    1.0      0.0
118   70    1   4     140.0     0  1.0      0.0    157.0    1.0      2.0
119   72    1   3     160.0     0  NaN      2.0    114.0    0.0      1.6
120   73    0   3     160.0     0  0.0      1.0    121.0    0.0      0.0
121   74    1   2     145.0     0  NaN      1.0    123.0    0.0      1.3

     slope   ca  thal  num
0      1.0  NaN   NaN    1
1      NaN  NaN   7.0    3
2      2.0  NaN   6.0    1
3      1.0  NaN   NaN    2
4      2.0  NaN   3.0    1
..     ...  ...   ...  ...
117    2.0  NaN   7.0    1
118    2.0  NaN   7.0    3
119    2.0  2.0   NaN    0
120    1.0  NaN   3.0    1
121    1.0  NaN   NaN    1

[122 rows x 14 columns]

In [30]:
df.fillna(df.mean(), inplace=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,34,1,4,115.0,0,0.104167,0.363636,154.0,0.0,0.200000,1.000000,1.6,5.788732,1
1,35,1,4,130.5,0,0.104167,0.000000,130.0,1.0,0.653448,1.809524,1.6,7.000000,3
2,36,1,4,110.0,0,0.104167,0.000000,125.0,1.0,1.000000,2.000000,1.6,6.000000,1
3,38,0,4,105.0,0,0.104167,0.000000,166.0,0.0,2.800000,1.000000,1.6,5.788732,2
4,38,0,4,110.0,0,0.000000,0.000000,156.0,0.0,0.000000,2.000000,1.6,3.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,70,1,4,115.0,0,0.000000,1.000000,92.0,1.0,0.000000,2.000000,1.6,7.000000,1
118,70,1,4,140.0,0,1.000000,0.000000,157.0,1.0,2.000000,2.000000,1.6,7.000000,3
119,72,1,3,160.0,0,0.104167,2.000000,114.0,0.0,1.600000,2.000000,2.0,5.788732,0
120,73,0,3,160.0,0,0.000000,1.000000,121.0,0.0,0.000000,1.000000,1.6,3.000000,1
121,74,1,2,145.0,0,0.104167,1.000000,123.0,0.0,1.300000,1.000000,1.6,5.788732,1

In [31]:
df =df[(df>=0).all(axis=1)]

In [32]:
print(df.isnull().sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
num         0
dtype: int64

In [17]:
X = df.drop("num", axis=1)
y = df["num"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [19]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))

Logistic Regression Accuracy: 0.28

In [21]:
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)

y_pred_knn =knn.predict(X_test)
print("KNN regression Accuracy:", accuracy_score(y_test, y_pred_knn))

KNN regression Accuracy: 0.52

In [22]:
print("LR Accuracy:", accuracy_score(y_test, y_pred_lr))
print("kNN Accuracy:", accuracy_score(y_test, y_pred_knn))

LR Accuracy: 0.28
kNN Accuracy: 0.52